Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "backstage-dev"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "backstage-dev"
    vb.memory = 8192
    vb.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.56.10"

  # monta o repo inteiro
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provision "shell", path: "provision.sh"
end
